spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ACC-Brijalan-Training/config-api.git
          clone-on-start: true
          default-label: main
